### ISSUE TITLE
Add asciimoji via rightclick

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [hpcodecraft/ASCIImoji#6]
Hello,

hopefully this is still alive. Can we have an additional field in the rightclick menu where all are listed in a big field. Like with a submenu für writing direction but instead of a simple list a list with 5-6 rows so it's easier to find one quickly. In the time I need to find an asciimoji in the addon I can just google it (Except for the ones you got in your head)

**Comment by hpcodecraft** [comment]
Hi @Exportforce, thanks for your suggestion, that is a great idea! I don't really get what you mean with "a list with 5-6 rows", how should it be organised then? If you have any ideas on that let me know. I rarely updated this extension lately, but I want to put some hours into it soon when I find the time :)

**Comment by Exportforce** [comment]
Hello,

don't know how to explain so I will do a super crappy screenshot of what I mean and hope it'll explain it enough.
This is the standard context menu for something: http://prntscr.com/jarc2n
You have the submenu with one single row of items, unscrollable. This one extended would be like this https://i.imgur.com/GeFsqPN.png it is now 2 rows. But since asciimojis are much smaller you can easily use 5 or more rows and make those scrollable to fit in everything like in a spreadsheet: http://prntscr.com/jarfpu

So you can do a rightclick into your common textfield, select the menu "Asciimoji" and the list pops up and you get a table like my example with like 5 rows (maybe configurabel?) and scroll up and down to look for the ones you like. Maybe a bonus on top: SHIFT+Click = Mark as Fav and this asciimoji will be always listed first.

Hope that explains it better.

**Comment by hpcodecraft** [comment]
Thanks for your explanation, I think I can imagine it now :) I'll see what I can do! Btw if you code yourself, I'd happily accept PRs, too ;)

**Comment by Exportforce** [comment]
I actually did code/programm stuff but those days are gone and I never did any addons for browsers. If I'd be able to do these, believe me. I had like a quadzillion extras for my browser.

Looking forward to it.

**Comment by hpcodecraft** [comment]
@Exportforce I just released version 1.5.0 which has the context menu.

**Comment by Exportforce** [comment]
Hmm says 1.4.3 for me even after clicking update, same with the chrome webstore being on 1.4.3
Will take a look later again.

**Comment by hpcodecraft** [comment]
(=^･ｪ･^=))ﾉ彡☆  <-- added with context menu. hmmm...

The spreadsheet layout wasn't possible btw, one row can only have one click handler, so I went for the alphabetical listing.
